// Lista padrão extraída da planilha "Check List Ronda C. Cirúrgico.xlsx" (96 equipamentos)
const checklistPadrao = [
    { patrimonio: "3133", descricao: "APARELHO DE ANESTESIA", fabricante: "GE", modelo: "CARESTATION 620", serie: "SM 618150017WA", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "3134", descricao: "APARELHO DE ANESTESIA", fabricante: "GE", modelo: "CARESTATION 620", serie: "SM 618150020WA", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "49269", descricao: "APARELHO DE ANESTESIA", fabricante: "MINDRAY", modelo: "WATO EX-30", serie: "DY-19001100", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "87779", descricao: "APARELHO DE ANESTESIA", fabricante: "MINDRAY", modelo: "WATO EX-30", serie: "DY-08002986", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "87780", descricao: "APARELHO DE ANESTESIA", fabricante: "MINDRAY", modelo: "WATO EX-30", serie: "DY-0B002987", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "87781", descricao: "APARELHO DE ANESTESIA", fabricante: "MINDRAY", modelo: "WATO EX-30", serie: "DY-08002985", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "2111", descricao: "ASPIRADOR CIRÚRGICO", fabricante: "FANEM", modelo: "DAB.089 AME", serie: "RAE36059", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "2772", descricao: "ASPIRADOR CIRÚRGICO", fabricante: "STRYKER", modelo: "5100-50A", serie: "42620", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "3179", descricao: "BAIR HUGGER", fabricante: "3M", modelo: "750", serie: "58323", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "28717", descricao: "BALANÇA ELETRÔNICA", fabricante: "WELMY", modelo: "R/I 109-E", serie: "6023", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "269", descricao: "BERÇO AQUECIDO", fabricante: "FANEM", modelo: "AMPLA", serie: "HAN 056638", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "13404", descricao: "BERÇO AQUECIDO", fabricante: "FANEM", modelo: "AMPLA 2085", serie: "DAB8429", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "2792", descricao: "BISTURI ELÉTRICO", fabricante: "WEM", modelo: "SS-501S", serie: "AAB0008088", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "2793", descricao: "BISTURI ELÉTRICO", fabricante: "WEM", modelo: "SS-501S", serie: "AAB0008089", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "2795", descricao: "BISTURI ELÉTRICO", fabricante: "WEM", modelo: "SS-501S", serie: "AAB0008092", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "2797", descricao: "BISTURI ELÉTRICO", fabricante: "WEM", modelo: "SS-501S", serie: "AAB0008087", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "2798", descricao: "BISTURI ELÉTRICO", fabricante: "WEM", modelo: "SS-501S", serie: "AAB0008090", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "2799", descricao: "BISTURI ELÉTRICO", fabricante: "WEM", modelo: "SS-501S", serie: "AAB0008085", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "10004", descricao: "BISTURI ELÉTRICO", fabricante: "WEM", modelo: "SS601MCA", serie: "656", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "", descricao: "BOMBA INFUSORA SERINGA", fabricante: "SAMTRONIC", modelo: "ST-7000 TCI", serie: "", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "", descricao: "BOMBA INFUSORA SERINGA", fabricante: "SAMTRONIC", modelo: "ST-7000 TCI", serie: "", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "", descricao: "BOMBA INFUSORA SERINGA", fabricante: "SAMTRONIC", modelo: "ST-7000 TCI", serie: "", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "", descricao: "BOMBA INFUSORA SERINGA", fabricante: "SAMTRONIC", modelo: "ST-7000 TCI", serie: "", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "", descricao: "BOMBA INFUSORA VOLUMÉTRICA", fabricante: "SAMTRONIC", modelo: "ST-1000", serie: "", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "", descricao: "BOMBA INFUSORA VOLUMÉTRICA", fabricante: "SAMTRONIC", modelo: "ST-1000", serie: "", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "", descricao: "BOMBA INFUSORA VOLUMÉTRICA", fabricante: "SAMTRONIC", modelo: "ST-1000", serie: "", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "", descricao: "BOMBA INFUSORA VOLUMÉTRICA", fabricante: "SAMTRONIC", modelo: "ST-1000", serie: "", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "2735", descricao: "BOMBA PARA HISTEROSCOPIA", fabricante: "STRYKER", modelo: "FLUID SAFE", serie: "1308CE490", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "3222", descricao: "CAIXA AQUECEDORA SORO", fabricante: "FANEM", modelo: "HEATER", serie: "YAP074309", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "3224", descricao: "CAIXA AQUECEDORA SORO", fabricante: "FANEM", modelo: "HEATER", serie: "YAP074310", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "2777", descricao: "CÂMERA DE VÍDEO", fabricante: "STRYKER", modelo: "ÓTICA", serie: "17F505214", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "2785", descricao: "CÂMERA DE VÍDEO", fabricante: "STRYKER", modelo: "ÓTICA", serie: "17G521884", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "202", descricao: "CARDIOVERSOR", fabricante: "PHILIPS", modelo: "DFM 100", serie: "CN 32610441", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "2738", descricao: "CONSOLE CÂMERA DE VIDEOCIRURGIA", fabricante: "STRYKER", modelo: "1488", serie: "17F556694", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "2784", descricao: "CONSOLE CÂMERA DE VIDEOCIRURGIA", fabricante: "STRYKER", modelo: "1488", serie: "17F556694", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "2718", descricao: "DETECTOR FETAL", fabricante: "MEDPEJ", modelo: "DF7001D", serie: "413197", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "10010", descricao: "EQUIPAMENTO ELETROESTIMULADOR", fabricante: "BBRAUM", modelo: "STIMUPLEX", serie: "106045", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "10018", descricao: "EQUIPAMENTO ELETROESTIMULADOR", fabricante: "BBRAUM", modelo: "STIMUPLEX", serie: "42011051", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "1358", descricao: "FOCO CIRÚRGICO MOVEL", fabricante: "MEDPEJ", modelo: "FL-2000AL", serie: "153168", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "257", descricao: "FOCO CIRÚRGICO TETO", fabricante: "SISMATEC", modelo: "3LE/3LE", serie: "1216724504", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "259", descricao: "FOCO CIRÚRGICO TETO", fabricante: "SISMATEC", modelo: "3LE/3LE", serie: "1216724505", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "260", descricao: "FOCO CIRÚRGICO TETO", fabricante: "SISMATEC", modelo: "3LE/3LE", serie: "1216724503", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "261", descricao: "FOCO CIRÚRGICO TETO", fabricante: "SISMATEC", modelo: "3LE/3LE", serie: "1216724502", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "262", descricao: "FOCO CIRÚRGICO TETO", fabricante: "SISMATEC", modelo: "3LE/3LE", serie: "1216724501", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "2737", descricao: "FONTE DE LUZ", fabricante: "STRYKER", modelo: "LED 9000", serie: "17C544704", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "2783", descricao: "FONTE DE LUZ", fabricante: "STRYKER", modelo: "LED 9000", serie: "17C544694", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "433", descricao: "INCUBADORA DE TRANSPORTE", fabricante: "FANEM", modelo: "IT -158/TS", serie: "CF 9440", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "2736", descricao: "INSUFLADOR VIDEOLAPAROSCOPIA", fabricante: "STRYKER", modelo: "PNEUMOSURE XL", serie: "1705CE0514", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "2782", descricao: "INSUFLADOR VIDEOLAPAROSCOPIA", fabricante: "STRYKER", modelo: "PNEUMOSURE XL", serie: "1705CE0517", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "176", descricao: "MESA CIRÚRGICA", fabricante: "BARRFAB", modelo: "BF-683 TDP", serie: "010-3261-116", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "239", descricao: "MESA CIRÚRGICA", fabricante: "BARRFAB", modelo: "BF 683T", serie: "010-3251-116", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "246", descricao: "MESA CIRÚRGICA", fabricante: "BARRFAB", modelo: "BF-683 TDP", serie: "010-3221-116", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "251", descricao: "MESA CIRÚRGICA", fabricante: "BARRFAB", modelo: "BF-683 TDP", serie: "010-3231-116", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "274", descricao: "MESA CIRÚRGICA", fabricante: "BARRFAB", modelo: "BF-683 TDP", serie: "010-3241-116", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "12783", descricao: "MESA CIRÚRGICA", fabricante: "BARRFAB", modelo: "BF-683 TDP", serie: "4886", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "186", descricao: "MÓDULO ANALIZADOR DE GASES", fabricante: "DIXTAL", modelo: "AGOI", serie: "170801663", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "187", descricao: "MÓDULO ANALIZADOR DE GASES", fabricante: "DIXTAL", modelo: "AGOI", serie: "170801659", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "267", descricao: "MÓDULO ANALIZADOR DE GASES", fabricante: "DIXTAL", modelo: "AGOI", serie: "170801665", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "267", descricao: "MÓDULO ANALIZADOR DE GASES", fabricante: "DIXTAL", modelo: "AGOI", serie: "170801665", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "271", descricao: "MÓDULO ANALIZADOR DE GASES", fabricante: "DIXTAL", modelo: "AGOI", serie: "170801664", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "3517", descricao: "MÓDULO DE CAPNOGRAFIA", fabricante: "DIXTAL", modelo: "ETCO2", serie: "171904110", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "3521", descricao: "MÓDULO DE PRESSÃO INVASIVA", fabricante: "DIXTAL", modelo: "IBP", serie: "160L17123", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "2740", descricao: "MONITOR DE VÍDEO", fabricante: "STRYKER", modelo: "VISIONPRO 26", serie: "VPD266L0285", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "2781", descricao: "MONITOR DE VÍDEO", fabricante: "STRYKER", modelo: "VISIONPRO 26", serie: "VPD267C0414", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "2640", descricao: "MONITOR DE VÍDEO NDS", fabricante: "MEDICAL DEVICE", modelo: "ENDOVUE 21", serie: "C16-004551", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "91", descricao: "MONITOR MULTIPARÂMETROS", fabricante: "DIXTAL", modelo: "DX2021", serie: "171509656", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "97", descricao: "MONITOR MULTIPARÂMETROS", fabricante: "DIXTAL", modelo: "DX2021", serie: "171509696", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "99", descricao: "MONITOR MULTIPARÂMETROS", fabricante: "DIXTAL", modelo: "DX2021", serie: "171509713", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "149", descricao: "MONITOR MULTIPARÂMETROS", fabricante: "DIXTAL", modelo: "DX2021", serie: "171509700", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "321", descricao: "MONITOR MULTIPARÂMETROS", fabricante: "DIXTAL", modelo: "DX2021", serie: "171509674", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "2580", descricao: "MONITOR MULTIPARÂMETROS", fabricante: "DIXTAL", modelo: "DX2021", serie: "171509687", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "2877", descricao: "MONITOR MULTIPARÂMETROS", fabricante: "DIXTAL", modelo: "DX2021", serie: "171311520", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "3110", descricao: "MONITOR MULTIPARÂMETROS", fabricante: "DIXTAL", modelo: "DX2021", serie: "171509670", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "4", descricao: "MONITOR MULTIPARÂMETROS", fabricante: "DIXTAL", modelo: "DX2020", serie: "171311540", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "265", descricao: "MONITOR MULTIPARÂMETROS", fabricante: "DIXTAL", modelo: "DX2020", serie: "171311590", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "270", descricao: "MONITOR MULTIPARÂMETROS", fabricante: "DIXTAL", modelo: "DX2020", serie: "171311570", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "2876", descricao: "MONITOR MULTIPARÂMETROS", fabricante: "DIXTAL", modelo: "DX2020", serie: "171311526", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "3113", descricao: "MONITOR MULTIPARÂMETROS", fabricante: "DIXTAL", modelo: "DX2020", serie: "171311512", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "2634", descricao: "PROCESSADORA ENDOSCOPIA", fabricante: "FUJIFILM", modelo: "EPX-2500", serie: "3V456G052", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "3327", descricao: "NOBREAK", fabricante: "SMS", modelo: "STATION II", serie: "273920287556", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "", descricao: "RACK C/RODIZIO", fabricante: "LABORMED", modelo: "5 DIVISÓRIAS", serie: "N/C", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "2739", descricao: "RACK PARA SISTEMA DE VIDEO", fabricante: "STRYKER", modelo: "5 DIVISÓRIAS", serie: "52753235", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "2780", descricao: "RACK PARA SISTEMA DE VIDEO", fabricante: "STRYKER", modelo: "5 DIVISÓRIAS", serie: "527546343", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "2679", descricao: "RAIO-X ARCO EM C", fabricante: "GE", modelo: "BRIVO - OEC", serie: "B3SS1700010", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "4184", descricao: "RAIO-X ARCO EM C", fabricante: "PHILIPS/VNI", modelo: "CENOS PLUS", serie: "1750020141", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "12784", descricao: "RAIO-X ARCO EM C", fabricante: "GE", modelo: "EVERVIEW 7500 GE", serie: "OECF2S08208", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "4100", descricao: "REANIMADOR INFANTIL", fabricante: "FANEM", modelo: "BABYPUFF 1020", serie: "FAS097843", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "4102", descricao: "REANIMADOR INFANTIL", fabricante: "FANEM", modelo: "BABYPUFF 1020", serie: "FAS097841", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "12781", descricao: "ULTRASSOM", fabricante: "FUJIFILM/SONOSITE", modelo: "MICROMAXX", serie: "03DX22", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "3052", descricao: "VAPORIZADOR CALIBRADO", fabricante: "PENLON", modelo: "SEVOFLURANE", serie: "D0214-0352", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "3136", descricao: "VAPORIZADOR CALIBRADO", fabricante: "DATEXOHMEDA", modelo: "SEVOFLURANE", serie: "BEJW02053", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "3188", descricao: "VAPORIZADOR CALIBRADO", fabricante: "DATEXOHMEDA", modelo: "TEC7 ISSO", serie: "BEGX1224", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "87783", descricao: "VAPORIZADOR CALIBRADO", fabricante: "MINDRAY", modelo: "SEVOFLURANE-V60", serie: "DK509245111", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "87784", descricao: "VAPORIZADOR CALIBRADO SERVO", fabricante: "MINDRAY", modelo: "V-60", serie: "DK509245097", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "2654", descricao: "VIDEOBRONCOSCOPIO", fabricante: "FUJIFILM", modelo: "EB-530H", serie: "1B087K265", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" },
    { patrimonio: "210", descricao: "VENTILADOR DE TRANSPORTE", fabricante: "DRAGER", modelo: "OXYLOG 3000 PLUS", serie: "ASKF-0111", inspecaoVisual: "", autoTeste: "", inspecaoAcessorios: "", ligadoRede: "" }
];
